import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header/Header";
import { ConfigProvider } from "antd";
import { THEME } from "@/styles/theme";
import React from "react";
import { MAIN_FONT } from "@/styles/font";
import SWRProvider from "@/components/provider/SWRProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${MAIN_FONT.className}`} suppressHydrationWarning>
      <body className="bg-secondary">
        <ConfigProvider
          theme={{
            token: {
              colorText: THEME.TEXT_COLOR,
              colorPrimary: THEME.PRIMARY_COLOR,
              fontFamily: MAIN_FONT.style.fontFamily
            },
            components: {
              Input: {
                activeBg: THEME.LIGHT_SECONDARY_COLOR,
                hoverBg: THEME.LIGHT_SECONDARY_COLOR,
                colorBgContainer: THEME.LIGHT_SECONDARY_COLOR,
                hoverBorderColor: THEME.HOVER_LIGHT_SECONDARY_COLOR,
                activeBorderColor: THEME.HOVER_LIGHT_SECONDARY_COLOR,
              },
              Menu: {
                itemBg: 'transparent',
              },
              Button: {
                defaultBg: THEME.LIGHT_SECONDARY_COLOR,
                defaultHoverBg: THEME.HOVER_LIGHT_SECONDARY_COLOR,
                defaultActiveBg: THEME.HOVER_LIGHT_SECONDARY_COLOR,
                lineWidth: 0
              }
            }
          }}
        >
          <SWRProvider>
            <Header />
            {children}
          </SWRProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
