import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header/Header"
import React from "react";
import {MAIN_FONT} from "@/styles/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${MAIN_FONT.className}`}>
        <body>
            <Header/>
            {children}
        </body>
    </html>
  );
}
