import { lightenDarkenColor } from "../utils/color";

const THEME = {
    PRIMARY_COLOR: '#FF2670',
    SECONDARY_COLOR: 'rgb(21,21,31)',
    LIGHT_SECONDARY_COLOR: '#2D2D3F',
    HOVER_LIGHT_SECONDARY_COLOR: '',
    LIGHT_PRIMARY_COLOR: '#c6e0f6',
    ROYAL_GRAY_COLOR: '#6F767E',
    DANGER_COLOR: '#FF4D4F',
    PRIMARY_ICON_COLOR: '#7D7C7C',
    TEXT_COLOR: '#FFFFFF',
    TEXT_HOVER_COLOR: 'rgb(178,178,193)',
    TEXT_MUTED_COLOR: 'rgb(178,178,193)'
    // LAYOUT_ELEMENT_SPACE: '0px',
    // LAYOUT_ELEMENT_BORDER_RADIUS: '0px',
    // BODY_PADDING: '0px'
};

THEME.HOVER_LIGHT_SECONDARY_COLOR = lightenDarkenColor(THEME.LIGHT_SECONDARY_COLOR, 20);

export { THEME };
