import { GameCategory, GameInfo, GamePlatform } from "@/interfaces/game";

export class GameAPI {
    static async getGameBySlug(slug: string): Promise<GameInfo> {
        return {
            name: "Axie Infinity",
            plug: "axie-infinity",
            img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Faxie-infinity-accessories%2FCard.png",
            visits: 1e6, items: 10000, offers: 5,
            categories: [GameCategory.Breeding, GameCategory.Card],
            platforms: [GamePlatform.Android, GamePlatform.iOS],
        }
    }

    static async getAllGames(): Promise<GameInfo[]> {
        return [
            {
                name: "Gods Unchained",
                plug: "gods-unchained",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Fgods-unchained%2FCard.png",
                visits: 100000,
                items: 50000,
                offers: 5,
                categories: [GameCategory.Card, GameCategory.PVP],
                platforms: [GamePlatform.Android, GamePlatform.Desktop],
            },
            {
                name: "Axie Infinity",
                plug: "axie-infinity",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Faxie-infinity-accessories%2FCard.png",
                visits: 1000000,
                items: 10000,
                offers: 5,
                categories: [GameCategory.Breeding, GameCategory.Card],
                platforms: [GamePlatform.Android, GamePlatform.iOS],
            },
            {
                name: "Pixels",
                plug: "pixels",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Fpixels---farm-land807754%2FCard.png",
                visits: 100000,
                items: 250,
                offers: 0,
                categories: [GameCategory.Adventure, GameCategory.MMORPG],
                platforms: [GamePlatform.Web],
            },
            {
                name: "Wild Forest",
                plug: "wild-forest",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Fwild-forest---units945084%2FCard.png",
                visits: 10000,
                items: 250,
                offers: 0,
                categories: [GameCategory.Card, GameCategory.PVP],
                platforms: [GamePlatform.Android, GamePlatform.iOS],
            },
            {
                name: "Pixels Spirit of Mimo",
                plug: "pixels-spirit-of-mimo091159",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Fpixels-spirit-of-mimo091159%2FCard.png",
                visits: 1000,
                items: 1000,
                offers: 0,
                categories: [],
                platforms: [],
            },
            {
                name: "Apeiron",
                plug: "apeiron",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Fapeiron---star-(ronin)331453%2FCard.png",
                visits: 100000,
                items: 500,
                offers: 0,
                categories: [GameCategory.Action, GameCategory.Adventure],
                platforms: [GamePlatform.Web],
            },
            {
                name: "Pixel Chibis NFT",
                plug: "pixels---chibis378201",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Fpixels---chibis378201%2FCard.png",
                visits: 0,
                items: 500,
                offers: 0,
                categories: [],
                platforms: [],
            },
            {
                name: "Parallel",
                plug: "parallel",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Fparallel-cosmetics-(llcm)362351%2FCard.png",
                visits: 100000,
                items: 500,
                offers: 0,
                categories: [GameCategory.Card, GameCategory.SciFi],
                platforms: [],
            },
            {
                name: "Moon Doonz - Pixels Avatars",
                plug: "doonz---pixels-avatars846846",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Fdoonz---pixels-avatars846846%2FCard.png",
                visits: 0,
                items: 500,
                offers: 0,
                categories: [],
                platforms: [],
            },
            {
                name: "Dizzy Demons",
                plug: "dizzy-demons---pixels-avatar372062",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Fdizzy-demons---pixels-avatar372062%2FCard.png",
                visits: 0,
                items: 1000,
                offers: 0,
                categories: [],
                platforms: [],
            },
            {
                name: "Pixel Porks",
                plug: "pixel-porks040135",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Fpixel-porks040135%2FCard.png",
                visits: 0,
                items: 250,
                offers: 0,
                categories: [],
                platforms: [],
            },
            {
                name: "Guild of Guardians",
                plug: "guild-of-guardians",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Fguild-of-guardians-items%2FCard.png",
                visits: 10000,
                items: 250,
                offers: 0,
                categories: [GameCategory.Action, GameCategory.Fantasy],
                platforms: [GamePlatform.Android, GamePlatform.iOS],
            },
            {
                name: "Ragnarok Monster World",
                plug: "ragnarok:-monster-world137662",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Fragnarok%3A-monster-world137662%2FCard.png",
                visits: 0,
                items: 250,
                offers: 0,
                categories: [],
                platforms: [],
            },
            {
                name: "CyberKongz",
                plug: "cyberkongz",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Fcyberkongz---vx-gear-(ronin)478641%2FCard.png",
                visits: 100000,
                items: 25,
                offers: 0,
                categories: [GameCategory.Breeding],
                platforms: [GamePlatform.Web],
            },
            {
                name: "Planet IX",
                plug: "planet-ix",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Fplanetix-land%2FCard.png",
                visits: 100000,
                items: 50,
                offers: 0,
                categories: [GameCategory.Sandbox, GameCategory.Simulation],
                platforms: [GamePlatform.Desktop],
            },
            {
                name: "Crypto Unicorns",
                plug: "crypto-unicorns",
                img: "https://image-cdn.lootrush.com/unsafe/800x0/smart/filters:format(webp)/https%3A%2F%2Flootrush-website-assets.s3.us-east-1.amazonaws.com%2Fimages%2Fgames%2Fcrypto-unicorns%2FCard.png",
                visits: 10000,
                items: 500,
                offers: 0,
                categories: [GameCategory.Breeding, GameCategory.Fantasy],
                platforms: [GamePlatform.Web],
            },
        ];

    }
}
